//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dental.DataLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int DataBaseNumber { get; set; }
        public string ID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int Version { get; set; }
        public string name { get; set; }
        public string SMSPracticeName { get; set; }
        public string notificationEmail { get; set; }
        public string address { get; set; }
        public string addressLine2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zipCode { get; set; }
        public string homePhone { get; set; }
        public string workPhone { get; set; }
        public string cellPhone { get; set; }
        public decimal balance { get; set; }
        public System.DateTime firstUpload { get; set; }
        public System.DateTime lastUpload { get; set; }
        public short software { get; set; }
        public string valetUserId { get; set; }
        public string valetPassword { get; set; }
        public string userId { get; set; }
        public string password { get; set; }
        public short accountStatus { get; set; }
        public string mainContact { get; set; }
        public string officeManager { get; set; }
        public short emailAuthorized { get; set; }
        public Nullable<int> nbUpload { get; set; }
        public string softwareDataPath { get; set; }
        public System.DateTime uploadSchedule { get; set; }
        public string synchonizationProcessing { get; set; }
        public string server { get; set; }
        public string webSite { get; set; }
        public short directionsProvider { get; set; }
        public short allowDirectLogin { get; set; }
        public string SecurityQuestion { get; set; }
        public string SecurityAnswer { get; set; }
        public System.DateTime SignupDate { get; set; }
        public string SmsSender { get; set; }
        public string SignupIp { get; set; }
        public short SMSAuthorized { get; set; }
        public string market { get; set; }
        public string accoutingEmail { get; set; }
        public string officeManagerFirstName { get; set; }
        public short PhoneAuthorized { get; set; }
        public short SyncLimitation { get; set; }
        public string varId { get; set; }
        public string defaultCreditCardId { get; set; }
        public short OLSAuthorized { get; set; }
        public short MobileAuthorized { get; set; }
        public short ReminderStatus { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string mainDoctorName { get; set; }
        public string ITContact { get; set; }
        public string ITPhone { get; set; }
        public string ITNoteId { get; set; }
        public short privateLabel { get; set; }
        public string GooglePlusURL { get; set; }
        public string FacebookPageURL { get; set; }
        public string GooglePlusPageId { get; set; }
        public string GooglePlusPublicName { get; set; }
        public short PostCardAuthorized { get; set; }
        public int PartnerActNbr { get; set; }
        public int GroupedWithDB { get; set; }
        public Nullable<short> SmsProvider { get; set; }
        public string SmsUserId { get; set; }
        public string SmsPassword { get; set; }
        public Nullable<short> SmsDeliveryConfirmation { get; set; }
        public string EmailSenderEmailAddress { get; set; }
        public string EmailSenderEmailDisplayedName { get; set; }
        public string EmailSenderSMTPserver { get; set; }
        public string EmailSenderSMTPport { get; set; }
        public Nullable<short> EmailSenderSMTPisSSL { get; set; }
        public string EmailSenderSMTPuserId { get; set; }
        public string EmailSenderSMTPpassword { get; set; }
        public short SecureMessageAuthorized { get; set; }
        public string TwitterURL { get; set; }
        public string LinkedInURL { get; set; }
        public Nullable<short> country { get; set; }
        public Nullable<System.DateTime> DeActivationDate { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<short> PetRecallStatus { get; set; }
        public Nullable<System.DateTime> LastDataMessageReceived { get; set; }
        public string PartnerUserName { get; set; }
    }
}
