//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dental.DataLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        public short DataBaseNumber { get; set; }
        public string ID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public short Version { get; set; }
        public short status { get; set; }
        public System.DateTime date { get; set; }
        public decimal amount { get; set; }
        public short tooth { get; set; }
        public short quadrant { get; set; }
        public string surface { get; set; }
        public short nbUnits { get; set; }
        public string stdTrtId { get; set; }
        public string patientId { get; set; }
        public string responsibleId { get; set; }
        public string officeVisitId { get; set; }
        public string providerId { get; set; }
    }
}
