//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5472.
// 
#pragma warning disable 1591

namespace WebServiceConsoleCall.webReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AvaVoipBinding", Namespace="urn:AvaVoip")]
    public partial class AvaVoip : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Appointmaster_GetLatestAccountsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Appointmaster_GetAccountsByTransIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback Appointmaster_GetAccountCampaignsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Appointmaster_GetAccountsCampaignsByTransIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback Appointmaster_GetCDRsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AvaVoip() {
            this.Url = global::WebServiceConsoleCall.Properties.Settings.Default.WebServiceConsoleCall_webReference_AvaVoip;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Appointmaster_GetLatestAccountsCompletedEventHandler Appointmaster_GetLatestAccountsCompleted;
        
        /// <remarks/>
        public event Appointmaster_GetAccountsByTransIDCompletedEventHandler Appointmaster_GetAccountsByTransIDCompleted;
        
        /// <remarks/>
        public event Appointmaster_GetAccountCampaignsCompletedEventHandler Appointmaster_GetAccountCampaignsCompleted;
        
        /// <remarks/>
        public event Appointmaster_GetAccountsCampaignsByTransIDCompletedEventHandler Appointmaster_GetAccountsCampaignsByTransIDCompleted;
        
        /// <remarks/>
        public event Appointmaster_GetCDRsCompletedEventHandler Appointmaster_GetCDRsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:AvaVoip#Appointmaster_GetLatestAccounts", RequestNamespace="urn:AvaVoip", ResponseNamespace="urn:AvaVoip")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public Response Appointmaster_GetLatestAccounts(CriteriaLatestAccountsList param, Auth auth) {
            object[] results = this.Invoke("Appointmaster_GetLatestAccounts", new object[] {
                        param,
                        auth});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void Appointmaster_GetLatestAccountsAsync(CriteriaLatestAccountsList param, Auth auth) {
            this.Appointmaster_GetLatestAccountsAsync(param, auth, null);
        }
        
        /// <remarks/>
        public void Appointmaster_GetLatestAccountsAsync(CriteriaLatestAccountsList param, Auth auth, object userState) {
            if ((this.Appointmaster_GetLatestAccountsOperationCompleted == null)) {
                this.Appointmaster_GetLatestAccountsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAppointmaster_GetLatestAccountsOperationCompleted);
            }
            this.InvokeAsync("Appointmaster_GetLatestAccounts", new object[] {
                        param,
                        auth}, this.Appointmaster_GetLatestAccountsOperationCompleted, userState);
        }
        
        private void OnAppointmaster_GetLatestAccountsOperationCompleted(object arg) {
            if ((this.Appointmaster_GetLatestAccountsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Appointmaster_GetLatestAccountsCompleted(this, new Appointmaster_GetLatestAccountsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:AvaVoip#Appointmaster_GetAccountsByTransID", RequestNamespace="urn:AvaVoip", ResponseNamespace="urn:AvaVoip")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public Response Appointmaster_GetAccountsByTransID(CriteriaAccountsByTransID param, Auth auth) {
            object[] results = this.Invoke("Appointmaster_GetAccountsByTransID", new object[] {
                        param,
                        auth});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void Appointmaster_GetAccountsByTransIDAsync(CriteriaAccountsByTransID param, Auth auth) {
            this.Appointmaster_GetAccountsByTransIDAsync(param, auth, null);
        }
        
        /// <remarks/>
        public void Appointmaster_GetAccountsByTransIDAsync(CriteriaAccountsByTransID param, Auth auth, object userState) {
            if ((this.Appointmaster_GetAccountsByTransIDOperationCompleted == null)) {
                this.Appointmaster_GetAccountsByTransIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAppointmaster_GetAccountsByTransIDOperationCompleted);
            }
            this.InvokeAsync("Appointmaster_GetAccountsByTransID", new object[] {
                        param,
                        auth}, this.Appointmaster_GetAccountsByTransIDOperationCompleted, userState);
        }
        
        private void OnAppointmaster_GetAccountsByTransIDOperationCompleted(object arg) {
            if ((this.Appointmaster_GetAccountsByTransIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Appointmaster_GetAccountsByTransIDCompleted(this, new Appointmaster_GetAccountsByTransIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:AvaVoip#Appointmaster_GetAccountCampaigns", RequestNamespace="urn:AvaVoip", ResponseNamespace="urn:AvaVoip")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public Response Appointmaster_GetAccountCampaigns(CriteriaAccountsCampaigns param, Auth auth) {
            object[] results = this.Invoke("Appointmaster_GetAccountCampaigns", new object[] {
                        param,
                        auth});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void Appointmaster_GetAccountCampaignsAsync(CriteriaAccountsCampaigns param, Auth auth) {
            this.Appointmaster_GetAccountCampaignsAsync(param, auth, null);
        }
        
        /// <remarks/>
        public void Appointmaster_GetAccountCampaignsAsync(CriteriaAccountsCampaigns param, Auth auth, object userState) {
            if ((this.Appointmaster_GetAccountCampaignsOperationCompleted == null)) {
                this.Appointmaster_GetAccountCampaignsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAppointmaster_GetAccountCampaignsOperationCompleted);
            }
            this.InvokeAsync("Appointmaster_GetAccountCampaigns", new object[] {
                        param,
                        auth}, this.Appointmaster_GetAccountCampaignsOperationCompleted, userState);
        }
        
        private void OnAppointmaster_GetAccountCampaignsOperationCompleted(object arg) {
            if ((this.Appointmaster_GetAccountCampaignsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Appointmaster_GetAccountCampaignsCompleted(this, new Appointmaster_GetAccountCampaignsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:AvaVoip#Appointmaster_GetAccountsCampaignsByTransID", RequestNamespace="urn:AvaVoip", ResponseNamespace="urn:AvaVoip")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public Response Appointmaster_GetAccountsCampaignsByTransID(CriteriaAccountsCampaignsByTransID param, Auth auth) {
            object[] results = this.Invoke("Appointmaster_GetAccountsCampaignsByTransID", new object[] {
                        param,
                        auth});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void Appointmaster_GetAccountsCampaignsByTransIDAsync(CriteriaAccountsCampaignsByTransID param, Auth auth) {
            this.Appointmaster_GetAccountsCampaignsByTransIDAsync(param, auth, null);
        }
        
        /// <remarks/>
        public void Appointmaster_GetAccountsCampaignsByTransIDAsync(CriteriaAccountsCampaignsByTransID param, Auth auth, object userState) {
            if ((this.Appointmaster_GetAccountsCampaignsByTransIDOperationCompleted == null)) {
                this.Appointmaster_GetAccountsCampaignsByTransIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAppointmaster_GetAccountsCampaignsByTransIDOperationCompleted);
            }
            this.InvokeAsync("Appointmaster_GetAccountsCampaignsByTransID", new object[] {
                        param,
                        auth}, this.Appointmaster_GetAccountsCampaignsByTransIDOperationCompleted, userState);
        }
        
        private void OnAppointmaster_GetAccountsCampaignsByTransIDOperationCompleted(object arg) {
            if ((this.Appointmaster_GetAccountsCampaignsByTransIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Appointmaster_GetAccountsCampaignsByTransIDCompleted(this, new Appointmaster_GetAccountsCampaignsByTransIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:AvaVoip#Appointmaster_GetCDRs", RequestNamespace="urn:AvaVoip", ResponseNamespace="urn:AvaVoip")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public Response Appointmaster_GetCDRs(CriteriaLPCDR param, Auth auth) {
            object[] results = this.Invoke("Appointmaster_GetCDRs", new object[] {
                        param,
                        auth});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void Appointmaster_GetCDRsAsync(CriteriaLPCDR param, Auth auth) {
            this.Appointmaster_GetCDRsAsync(param, auth, null);
        }
        
        /// <remarks/>
        public void Appointmaster_GetCDRsAsync(CriteriaLPCDR param, Auth auth, object userState) {
            if ((this.Appointmaster_GetCDRsOperationCompleted == null)) {
                this.Appointmaster_GetCDRsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAppointmaster_GetCDRsOperationCompleted);
            }
            this.InvokeAsync("Appointmaster_GetCDRs", new object[] {
                        param,
                        auth}, this.Appointmaster_GetCDRsOperationCompleted, userState);
        }
        
        private void OnAppointmaster_GetCDRsOperationCompleted(object arg) {
            if ((this.Appointmaster_GetCDRsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Appointmaster_GetCDRsCompleted(this, new Appointmaster_GetCDRsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5473")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:AvaVoip")]
    public partial class CriteriaLatestAccountsList {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5473")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:AvaVoip")]
    public partial class CriteriaLPCDR {
        
        private int dateField;
        
        /// <remarks/>
        public int Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5473")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:AvaVoip")]
    public partial class CriteriaAccountsCampaignsByTransID {
        
        private int accountIdField;
        
        private int transactionIdField;
        
        /// <remarks/>
        public int AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public int TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5473")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:AvaVoip")]
    public partial class CriteriaAccountsCampaigns {
        
        private int accountIdField;
        
        /// <remarks/>
        public int AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5473")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:AvaVoip")]
    public partial class CriteriaAccountsByTransID {
        
        private int transactionIdField;
        
        /// <remarks/>
        public int TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5473")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:AvaVoip")]
    public partial class Response {
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private string transIDField;
        
        private string[] listField;
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string TransID {
            get {
                return this.transIDField;
            }
            set {
                this.transIDField = value;
            }
        }
        
        /// <remarks/>
        public string[] List {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5473")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:AvaVoip")]
    public partial class Auth {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void Appointmaster_GetLatestAccountsCompletedEventHandler(object sender, Appointmaster_GetLatestAccountsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Appointmaster_GetLatestAccountsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Appointmaster_GetLatestAccountsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void Appointmaster_GetAccountsByTransIDCompletedEventHandler(object sender, Appointmaster_GetAccountsByTransIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Appointmaster_GetAccountsByTransIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Appointmaster_GetAccountsByTransIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void Appointmaster_GetAccountCampaignsCompletedEventHandler(object sender, Appointmaster_GetAccountCampaignsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Appointmaster_GetAccountCampaignsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Appointmaster_GetAccountCampaignsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void Appointmaster_GetAccountsCampaignsByTransIDCompletedEventHandler(object sender, Appointmaster_GetAccountsCampaignsByTransIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Appointmaster_GetAccountsCampaignsByTransIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Appointmaster_GetAccountsCampaignsByTransIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void Appointmaster_GetCDRsCompletedEventHandler(object sender, Appointmaster_GetCDRsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Appointmaster_GetCDRsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Appointmaster_GetCDRsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591