//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AM.VetData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicSpecies
    {
        public int ID { get; set; }
        public Nullable<int> ClinicID { get; set; }
        public Nullable<int> SpeciesID { get; set; }
        public Nullable<bool> PrimaryDisplay { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual Species Species { get; set; }
    }
}
