//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AM.VetData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinic
    {
        public Clinic()
        {
            this.Appointments = new HashSet<Appointment>();
            this.ClinicSpecies = new HashSet<ClinicSpecies>();
            this.APIUsers = new HashSet<APIUser>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string StateProvince { get; set; }
        public string PostalCode { get; set; }
        public string WebAddress { get; set; }
        public string EmailAddress { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public byte[] Logo { get; set; }
        public string DefaultCultureCode { get; set; }
        public string PrimaryColor { get; set; }
        public string SecondaryColor { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual Culture Culture { get; set; }
        public virtual ICollection<ClinicSpecies> ClinicSpecies { get; set; }
        public virtual ICollection<APIUser> APIUsers { get; set; }
    }
}
