//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AM.VetData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Culture
    {
        public Culture()
        {
            this.Clients = new HashSet<Client>();
            this.Clinics = new HashSet<Clinic>();
        }
    
        public string CultureCode { get; set; }
        public string CountryCode { get; set; }
        public string LanguageCode { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
        public virtual ICollection<Clinic> Clinics { get; set; }
    }
}
