//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dental.DataLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int DataBaseNumber { get; set; }
        public string ID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public short Version { get; set; }
        public string name { get; set; }
        public string firstName { get; set; }
        public string title { get; set; }
        public string SSN { get; set; }
        public short male { get; set; }
        public System.DateTime birthDate { get; set; }
        public string address { get; set; }
        public string addressLine2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zipCode { get; set; }
        public string homePhone { get; set; }
        public string workPhone { get; set; }
        public string cellPhone { get; set; }
        public decimal balance { get; set; }
        public short status { get; set; }
        public short maritalStatus { get; set; }
        public System.DateTime firstVisit { get; set; }
        public System.DateTime lastVisit { get; set; }
        public string email { get; set; }
        public string responsiblePartyId { get; set; }
        public string providerId { get; set; }
        public string assistantId { get; set; }
        public string referedById { get; set; }
        public string employerId { get; set; }
        public string insur1 { get; set; }
        public string insur2 { get; set; }
        public string planId { get; set; }
        public string otherPhone { get; set; }
        public short language { get; set; }
        public string officeId { get; set; }
    }
}
